version: '2'
services:
  db:
    image: postgres
  web:
    build: build
    command: bash -c "glide install && go build main.go && ./main"
    working_dir: /go/src/github.com/ReconfigureIO/platform
    volumes:
      - .:/go/src/github.com/ReconfigureIO/platform
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
