version: '2.1'
services:
  db:
    image: postgres:alpine
    networks:
      - platform

  minio:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /buckets/reconfigureio-builds && mkdir -p /buckets/testbucket.reconfigure.io && /usr/bin/minio server /buckets'
    environment:
      - MINIO_ACCESS_KEY=foo
      - MINIO_SECRET_KEY=foobarbaz
      - MINIO_DOMAIN=minio.test
    ports:
      - "9000:9000"
    networks:
      platform:
        aliases:
          - reconfigureio-builds.minio.test
          - testbucket.reconfigure.io.minio.test

  web-base:
    build: build
    working_dir: /go/src/github.com/ReconfigureIO/platform
    volumes:
      - .:/go/src/github.com/ReconfigureIO/platform
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foobarbaz
      - S3_ENDPOINT=http://minio.test:9000/
      - RECO_AWS_ENDPOINT=http://fake-batch.test:9090
      - AWS_REGION=us-east-1
      - DATABASE_URL=host=db user=postgres dbname=postgres sslmode=disable password=mysecretpassword
      - PORT=8080
      - RECO_PLATFORM_MIGRATE=1
      - RECO_FEATURE_BILLING=1
      - RECO_FEATURE_DEPLOY=0
      - RECO_ENV=development
      - RECO_HOST_NAME=local.reconfigure.io
      - RECO_FEATURE_DEP_QUEUE=1
      - RECO_PUBLIC_PROJECT_ID=a95550bf-bffa-42df-b100-872501940c5c

  test:
    extends: web-base
    depends_on:
      - db
      - web-base
      - minio
      - fake-batch
    networks:
      - platform

  fake-batch:
    extends: web-base
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web-base
      - minio
    networks:
      platform:
        aliases:
          - fake-batch.test
    environment:
      - FAKE_BATCH_WORKER_NETWORK=platform_platform
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foobarbaz
      - S3_ENDPOINT=http://minio.test:9000/
    command: bash -c "make clean dist-image/dist/fake-batch && ./dist-image/dist/fake-batch"

  web:
    command: bash -c "fresh"
    extends: web-base
    ports:
      - "8080:80"
    depends_on:
      - db
      - minio
      - fake-batch
    networks:
      platform:
        aliases:
          - local.reconfigure.io
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foobarbaz
      - S3_ENDPOINT=http://minio.test:9000/
      - RECO_AWS_ENDPOINT=http://fake-batch.test:9090
      - AWS_REGION=us-east-1
      - DATABASE_URL=host=db user=postgres dbname=postgres sslmode=disable password=mysecretpassword
      - PORT=80
      - RECO_PLATFORM_MIGRATE=1
      - RECO_FEATURE_BILLING=1
      - RECO_FEATURE_DEPLOY=0
      - RECO_ENV=development-on-prem
      - RECO_HOST_NAME=local.reconfigure.io
      - RECO_FEATURE_DEP_QUEUE=1
      - RECO_PUBLIC_PROJECT_ID=a95550bf-bffa-42df-b100-872501940c5c

networks:
  platform:
    driver: bridge
    driver_opts:
      name: "platform"