version: '2'
services:
  db:
    image: postgres:alpine

  minio:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /buckets/reconfigureio-builds && mkdir -p /buckets/testbucket.reconfigure.io && /usr/bin/minio server /buckets'
    environment:
      - MINIO_ACCESS_KEY=foo
      - MINIO_SECRET_KEY=foobarbaz
      - MINIO_DOMAIN=minio
    ports:
      - "9000:9000" 

  web-base:
    build: build
    working_dir: /go/src/github.com/ReconfigureIO/platform
    volumes:
      - .:/go/src/github.com/ReconfigureIO/platform
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foobarbaz
      - S3_ENDPOINT=http://minio:9000/
      - RECO_AWS_ENDPOINT=http://fake-batch:9090
      - AWS_REGION=us-east-1
      - DATABASE_URL=host=db user=postgres dbname=postgres sslmode=disable password=mysecretpassword
      - PORT=8080
      - RECO_PLATFORM_MIGRATE=1
      - RECO_FEATURE_BILLING=1
      - RECO_FEATURE_DEPLOY=0
      - RECO_ENV=development
      - RECO_HOST_NAME=local.reconfigure.io
      - RECO_FEATURE_DEP_QUEUE=1
      - RECO_PUBLIC_PROJECT_ID=a95550bf-bffa-42df-b100-872501940c5c

  fake-batch:
    extends: web-base
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web-base
      - minio
    links:
      - minio:reconfigureio-builds.minio
    command: bash -c "make clean dist-image/dist/fake-batch && ./dist-image/dist/fake-batch"

  web:
    command: bash -c "fresh"
    extends: web-base
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
      - fake-batch
    links:
      - db
      - fake-batch
      - minio:reconfigureio-builds.minio
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foobarbaz
      - S3_ENDPOINT=http://minio:9000/
      - RECO_AWS_ENDPOINT=http://fake-batch:9090
      - AWS_REGION=us-east-1
      - DATABASE_URL=host=db user=postgres dbname=postgres sslmode=disable password=mysecretpassword
      - PORT=8080
      - RECO_PLATFORM_MIGRATE=1
      - RECO_FEATURE_BILLING=1
      - RECO_FEATURE_DEPLOY=0
      - RECO_ENV=development-on-prem
      - RECO_HOST_NAME=local.reconfigure.io
      - RECO_FEATURE_DEP_QUEUE=1
      - RECO_PUBLIC_PROJECT_ID=a95550bf-bffa-42df-b100-872501940c5c
