version: '2'
services:
  db:
    image: postgres:alpine
  web:
    build: build
    command: bash -c "glide install && fresh"
    working_dir: /go/src/github.com/ReconfigureIO/platform
    volumes:
      - .:/go/src/github.com/ReconfigureIO/platform
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GITHUB_CLIENT_ID=c405f7d899fa411aaa69
      - GITHUB_CLIENT_SECRET=0105d6cd1bea780f5ecf651351f2579277f80b14
      - DATABASE_URL=host=db user=postgres dbname=postgres sslmode=disable password=mysecretpassword
      - PORT=8080
      - RECO_PLATFORM_MIGRATE=1
      - RECO_FEATURE_BILLING=1
      - STRIPE_KEY=sk_test_NvEpeLnLAV15b9TWJzZKLkvW
