version: '2'
services:
  db:
    image: postgres:alpine
  web-base:
    build: build
    working_dir: /go/src/github.com/ReconfigureIO/platform
    volumes:
      - .:/go/src/github.com/ReconfigureIO/platform
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - RECO_INTERCOM_ACCESS_TOKEN
      - LOGZIO_TOKEN
      - GITHUB_CLIENT_ID=c405f7d899fa411aaa69
      - GITHUB_CLIENT_SECRET=0105d6cd1bea780f5ecf651351f2579277f80b14
      - DATABASE_URL=host=db user=postgres dbname=postgres sslmode=disable password=mysecretpassword
      - PORT=8080
      - RECO_PLATFORM_MIGRATE=1
      - RECO_FEATURE_BILLING=1
      - RECO_FEATURE_DEPLOY=1
      - RECO_ENV=development
      - STRIPE_KEY=sk_test_NvEpeLnLAV15b9TWJzZKLkvW
      - RECO_DEPLOY_AMI=ami-8e6a4df5
  test:
    extends: web-base
    depends_on:
      - db
    links:
      - db
  web:
    command: bash -c "glide install && fresh"
    extends: web-base
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

  cron:
    extends: web-base
    ports:
      - "8000:8080"
    depends_on:
      - db
      - web
    links:
      - db
    command: bash -c "make clean all && glide install && ./dist-image/dist/worker"
