apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reconfigureio-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reconfigureio-api
    spec:
      containers:
      - name: api
        image: reconfigureio/api:latest
        ports:
        - containerPort: 80
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name:
          value:
        - name:
          value:
        - name:
          value:
        - name:
          value:
        - name:
          value:
        - name:
          value:
        - name:
          value:
        - name:
          value:
        
        - name: DATABASE_URL
          value: foo
        - name: SECRET_KEY_BASE
          value: bar
        - name: STRIPE_KEY
          value: baz
        - name: PORT
          value: "80"
        - name: RECO_ENV #reco short for reconfigure.io
          value: production
        - name: RECO_PLATFORM_MIGRATE
          value: "true"
        - name: RECO_FEATURE_DEPLOY
          value: "true"
        - name: RECO_AWS_LOG_GROUP
          value: "/aws/batch/job"
        - name: RECO_AWS_BUCKET
          value: reconfigureio-builds
        - name: RECO_AWS_QUEUE
          value: build-jobs
        - name: RECO_AWS_JOB
          value: sdaccel-builder-build
        - name: RECO_FEATURE_DEPLOY
          value: "true"
        - name: RECO_DEPLOY_LOG_GROUP
          value: "/reconfigureio/deployments"
        - name: RECO_DEPLOY_IMAGE
          value: "reconfigureio/docker-aws-fpga-runtime:latest"
        - name: RECO_DEPLOY_AMI
          value: foo
        - name: RECO_DEPLOY_BUCET
          value: "reconfigureio-builds"


    AWS_REGION: us-east-1
    PORT: '8080'
    RECO_FEATURE_BILLING: 1
    RECO_FEATURE_DEPLOY: 1
    GITHUB_CLIENT_ID: ssm:///reconfigureio/platform/staging/github_client
    GITHUB_CLIENT_SECRET: ssm:///reconfigureio/platform/staging/github_secret
    STRIPE_KEY: ssm:///reconfigureio/platform/staging/stripe
    DATABASE_URL: ssm:///reconfigureio/platform/staging/db
    RECO_DEPLOY_AMI: ami-8e6a4df5
    RECO_AWS_QUEUE: staging-build-jobs
    RECO_AWS_JOB: sdaccel-builder-build-staging