apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reconfigureio-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reconfigureio-api
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::398048034572:role/api-web-server
    spec:
      containers:
      - name: api
        image: 398048034572.dkr.ecr.us-east-1.amazonaws.com/reconfigureio/api:latest
        ports:
        - containerPort: 80
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: GITHUB_CLIENT_ID
          value: ssm:///reconfigureio/platform/production/github_client
        - name: GITHUB_CLIENT_SECRET
          value: ssm:///reconfigureio/platform/production/github_secret  
        - name: DATABASE_URL
          value: ssm:///reconfigureio/platform/production/db
        - name: SECRET_KEY_BASE
          value: foobar
        - name: STRIPE_KEY
          value: ssm:///reconfigureio/platform/production/stripe
        - name: PORT
          value: "80"
        - name: RECO_ENV #reco short for reconfigure.io
          value: production
        - name: RECO_PLATFORM_MIGRATE
          value: "true"
        - name: RECO_FEATURE_DEPLOY
          value: "true"
        - name: RECO_AWS_LOG_GROUP
          value: "/aws/batch/job"
        - name: RECO_AWS_BUCKET
          value: reconfigureio-builds
        - name: RECO_AWS_QUEUE
          value: build-jobs
        - name: RECO_AWS_JOB
          value: sdaccel-builder-build
        - name: RECO_FEATURE_DEPLOY
          value: "true"
        - name: RECO_DEPLOY_LOG_GROUP
          value: "/reconfigureio/deployments"
        - name: RECO_DEPLOY_IMAGE
          value: "reconfigureio/docker-aws-fpga-runtime:latest"
        - name: RECO_DEPLOY_AMI
          value: ami-8e6a4df5
        - name: RECO_DEPLOY_BUCET
          value: "reconfigureio-builds"
 