apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-production
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: migrate-production
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::398048034572:role/api-web-server
    spec:
      restartPolicy: Never
      containers:
      - name: migrate-production
        image: foo
        command: ["ssm-env"]
        args: ["/deploy_schema"]
        envFrom:
          - configMapRef:
              name: production-config
