branch-defaults:
  default:
    environment: worker-production
    group_suffix: production
global:
  application_name: platform
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
