apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-config
  namespace: default
data:
 AWS_REGION: "us-east-1"
 GITHUB_CLIENT_ID: ssm:///reconfigureio/platform/staging/github_client
 GITHUB_CLIENT_SECRET: ssm:///reconfigureio/platform/staging/github_secret
 DATABASE_URL: ssm:///reconfigureio/platform/staging/db
 SECRET_KEY_BASE: foobar
 STRIPE_KEY: ssm:///reconfigureio/platform/staging/stripe
 LOGZIO_TOKEN: ssm:///reconfigureio/platform/production/logzio_token
 PORT: "80"
 RECO_ENV: staging
 RECO_PLATFORM_MIGRATE: "false"
 RECO_AWS_LOG_GROUP: "/aws/batch/job"
 RECO_AWS_BUCKET: reconfigureio-builds
 RECO_AWS_QUEUE: staging-build-jobs
 RECO_AWS_JOB: sdaccel-builder-build-staging
 RECO_DEPLOY_LOG_GROUP: "/reconfigureio/deployments"
 RECO_DEPLOY_IMAGE: "reconfigureio/docker-aws-fpga-runtime:latest"
 RECO_DEPLOY_AMI: ami-43338239
 RECO_DEPLOY_SUBNET: subnet-ef8096b5
 RECO_DEPLOY_BUCKET: "reconfigureio-builds"
 RECO_FEATURE_USE_SPOT_INSTANCES: "true"
 RECO_FEATURE_DEP_QUEUE: "true"
 RECO_HOST_NAME: "staging-api.reconfigure.io"
