AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentTier:
  Name: Worker
  Type: SQS/HTTP
OptionSettings:
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t2.micro
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:elasticbeanstalk:environment:
    LoadBalancerType: classic
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:healthreporting:system:
    SystemType: enhanced
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on 64bit
    Amazon Linux/2.5.2
branch-defaults:
  default:
    environment: web-production
    group_suffix: production
global:
  application_name: platform
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: us-east-1
  instance_profile: aws-arn:aws:iam::398048034572:role/aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
