- hosts: tag_service_testing_on_prem
  become: yes

  post_tasks:
    - name: install docker-compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Make docker-compose executable 
      file:
        path: /usr/local/bin/docker-compose
        mode: 0777

    - name: docker login to ECR
      shell: aws ecr get-login --region us-east-1 --no-include-email | bash

    - name: docker pull compiler image from ECR
      command: docker image pull 398048034572.dkr.ecr.us-east-1.amazonaws.com/reconfigureio/build-framework/sdaccel-builder:v0.17.5 

    - name: install rsync so we can use the fast synchronize function instead of copy
      yum:
        name: rsync
        state: latest

    - name: copy using rsync platform directory to test machine
      synchronize:
        src: ../../platform
        dest: /home/centos/

    - name: docker-compose up (leave that running)
      shell: cd /home/centos/platform/; nohup /usr/local/bin/docker-compose -f docker-compose.on-prem.yml up </dev/null >/dev/null 2>&1 &

    - name: gather facts about EC2 instance
      ec2_facts:

    - name: print instance IP and command for SSH-ing
      debug:
        msg: "Instance ready, connect and port-forward by running ssh -L 8080:localhost:8080 centos@{{ ansible_ec2_public_hostname }}"

