- hosts: localhost
  gather_facts: False
  
  vars:
    ami_id: ami-9cf451e1

  tasks:
    - name: Provision on-prem instance
      ec2:
         key_name: "{{ lookup('env', 'AWS_KEYPAIR') }}"
         instance_type: "t2.xlarge"
         image: "{{ ami_id }}"
         wait: true
         exact_count: 1
         region: "{{ lookup('env', 'AWS_REGION') }}"
         groups: ['default']
         count_tag:
            service: testing-on-prem
         instance_tags:
            service: testing-on-prem
            owner: "{{ lookup('env', 'USER') }}"
         volumes:           
           - device_name: /dev/xvda
             volume_size: 150
             delete_on_termination: true
             volume_type: gp2
         instance_profile_name: ecsInstanceRole
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=60 timeout=320 state=started
      when: ec2.changed and item.state != "terminated"
      with_items: '{{ec2.instances}}'

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=tag_service_testing_on_prem
      with_items: '{{ec2.instances}}'
